import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/Navbar";
import Loading from "./loading";
import { Analytics } from "@vercel/analytics/react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  // Optional: Use as variable if you want to combine with other fonts
  // variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Cyborg Robotics Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} antialiased`}>
        <NavbarDemo />
        <Loading />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
